# Generated by Django 5.2.3 on 2025-07-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycollege', '0002_alter_bakeryitem_image_alter_canteenitem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakeryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Bakery_images/'),
        ),
        migrations.AlterField(
            model_name='canteenitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='canteen_images/'),
        ),
        migrations.AlterField(
            model_name='messitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Mess_images/'),
        ),
    ]
